# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GuiaDeCampoDialog
                                 A QGIS plugin
 Gerao de PDFs com hiperlinks georreferenciados.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-18
        git sha              : $Format:%H$
        copyright            : (C) 2026 by FARM Analytica
        email                : caio.arantes@farmanaltyica.com.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtCore, QtGui, QtWidgets


def _qt_enum(scoped_name, member_name, legacy_name):
    """Return a Qt5/Qt6 compatible enum member."""
    scoped_enum = getattr(QtCore.Qt, scoped_name, None)
    if scoped_enum is not None:
        return getattr(scoped_enum, member_name)
    return getattr(QtCore.Qt, legacy_name)


class GuiaDeCampoDialog(QtWidgets.QDialog):
    """Main plugin dialog built in code (no .ui dependency)."""

    def __init__(self, plugin_language='en', parent=None):
        """Create all controls used by service actions."""
        super(GuiaDeCampoDialog, self).__init__(parent)
        self.plugin_language = plugin_language

        self.setWindowTitle(self._t('Field Guide', 'Field Guide'))
        self.setWindowFlag(_qt_enum('WindowType', 'WindowStaysOnTopHint', 'WindowStaysOnTopHint'), True)
        self.setWindowFlag(_qt_enum('WindowType', 'WindowMinimizeButtonHint', 'WindowMinimizeButtonHint'), True)
        self.resize(560, 720)
        self.setMinimumSize(520, 640)
        self.setStyleSheet(self._build_stylesheet())

        root_layout = QtWidgets.QVBoxLayout(self)
        root_layout.setContentsMargins(12, 10, 12, 10)
        root_layout.setSpacing(10)

        scroll_area = QtWidgets.QScrollArea(self)
        scroll_area.setWidgetResizable(True)
        scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        root_layout.addWidget(scroll_area)

        content = QtWidgets.QWidget(self)
        scroll_area.setWidget(content)

        layout = QtWidgets.QVBoxLayout(content)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(10)

        self._build_header(layout)
        self._build_capture_group(layout)
        self._build_state_group(layout)
        self._build_manual_group(layout)
        self._build_manage_group(layout)
        self._build_output_group(layout)
        self._build_about_group(layout)
        layout.addStretch(1)

        self.mark_on_canvas_checkbox.toggled.connect(self.update_capture_status)
        self.update_capture_status(self.mark_on_canvas_checkbox.isChecked())
        self.set_points([])

    def _build_stylesheet(self):
        """Return dialog stylesheet."""
        return """
        QDialog {
            background: #f7fafc;
            color: #1a202c;
        }
        QScrollArea {
            background: transparent;
        }
        QLabel {
            color: #1a202c;
        }
        QLabel#titleLabel {
            font-size: 20px;
            font-weight: 700;
            color: #12324a;
        }
        QLabel#descriptionLabel {
            color: #4a5568;
            line-height: 1.4;
        }
        QLabel#websiteLabel {
            color: #2b6cb0;
            font-size: 11px;
            font-weight: 600;
        }
        QLabel#sectionHintLabel {
            color: #4a5568;
            font-size: 11px;
        }
        QLabel#statusBadge {
            border-radius: 11px;
            padding: 4px 10px;
            font-size: 11px;
            font-weight: 700;
        }
        QLabel#statusBadge[inactive="true"] {
            background: #edf2f7;
            color: #4a5568;
            border: 1px solid #cbd5e0;
        }
        QLabel#statusBadge[inactive="false"] {
            background: #e6fffa;
            color: #234e52;
            border: 1px solid #81e6d9;
        }
        QGroupBox {
            border: 1px solid #d7e0ea;
            border-radius: 12px;
            margin-top: 10px;
            padding-top: 10px;
            font-weight: 700;
            background: #ffffff;
        }
        QGroupBox::title {
            subcontrol-origin: margin;
            left: 12px;
            padding: 0 4px;
            color: #12324a;
        }
        QPushButton {
            min-height: 32px;
            border-radius: 8px;
            border: 1px solid #cbd5e0;
            padding: 5px 10px;
            font-weight: 600;
            background-color: #f7fafc;
            color: #1a202c;
        }
        QPushButton:hover {
            background-color: #edf2f7;
        }
        QPushButton:pressed {
            background-color: #e2e8f0;
        }
        QPushButton:disabled {
            color: #90a4b7;
            background-color: #f8fafc;
            border-color: #e2e8f0;
        }
        QPushButton#hybridButton {
            background-color: #ebfff7;
            border: 1px solid #8bd5be;
            color: #1f5f53;
        }
        QPushButton#hybridButton:hover {
            background-color: #d7f8ec;
        }
        QPushButton#routeAllButton {
            background-color: #ebfff7;
            border: 1px solid #5cc7b6;
            color: #1f5f53;
        }
        QPushButton#routeAllButton:hover {
            background-color: #d7f8ec;
        }
        QPushButton#clearButton {
            background-color: #fff5f5;
            border: 1px solid #feb2b2;
            color: #742a2a;
        }
        QPushButton#clearButton:hover {
            background-color: #fed7d7;
        }
        QPushButton#removeLastButton {
            background-color: #fffbea;
            border: 1px solid #ecc94b;
            color: #744210;
        }
        QPushButton#removeLastButton:hover {
            background-color: #faf089;
        }
        QPushButton#csvExportButton {
            background-color: #f0fff4;
            border: 1px solid #9ae6b4;
            color: #22543d;
        }
        QPushButton#csvExportButton:hover {
            background-color: #c6f6d5;
        }
        QPushButton#csvImportButton {
            background-color: #fffaf0;
            border: 1px solid #f6ad55;
            color: #744210;
        }
        QPushButton#csvImportButton:hover {
            background-color: #feebc8;
        }
        QPushButton#generateButton {
            background-color: #2b6cb0;
            border: 1px solid #2c5282;
            color: #ffffff;
        }
        QPushButton#generateButton:hover {
            background-color: #2c5282;
        }
        QPushButton#generateButton:pressed {
            background-color: #1a365d;
        }
        QPushButton#manualAddButton {
            background-color: #ebf8ff;
            border: 1px solid #90cdf4;
            color: #1a365d;
        }
        QPushButton#manualAddButton:hover {
            background-color: #bee3f8;
        }
        QCheckBox {
            spacing: 6px;
            color: #1a202c;
            font-weight: 600;
            padding: 2px 2px;
        }
        QCheckBox::indicator {
            width: 18px;
            height: 18px;
            border-radius: 4px;
            border: 1px solid #a0aec0;
            background: #ffffff;
        }
        QCheckBox::indicator:hover {
            border: 1px solid #2b6cb0;
            background: #ebf8ff;
        }
        QCheckBox::indicator:checked {
            border: 1px solid #2b6cb0;
            background: #2b6cb0;
            image: url(:/images/themes/default/mIconSuccess.svg);
        }
        QLineEdit {
            min-height: 30px;
            border: 1px solid #cbd5e0;
            border-radius: 8px;
            padding: 4px 8px;
            background: #ffffff;
            color: #1a202c;
        }
        QLineEdit:focus {
            border: 1px solid #2b6cb0;
        }
        QListWidget {
            border: 1px solid #d7e0ea;
            border-radius: 10px;
            background: #f8fbfd;
            padding: 4px;
        }
        QListWidget::item {
            padding: 7px 8px;
            margin: 2px 0;
            border-radius: 6px;
        }
        QListWidget::item:selected {
            background: #dbeafe;
            color: #12324a;
        }
        QFrame#lineSeparator {
            background: #e2e8f0;
            max-height: 1px;
        }
        """

    def _build_header(self, layout):
        """Build top header area."""
        title_label = QtWidgets.QLabel(self._t('Field Guide', 'Field Guide'), self)
        title_label.setObjectName('titleLabel')
        layout.addWidget(title_label)

        description = QtWidgets.QLabel(
            self._t(
                'Capture points on the map, review them in a live list, and export routes or PDF outputs when ready.',
                'Capture pontos no mapa, acompanhe a lista em tempo real e exporte rotas ou PDFs quando estiver pronto.',
            ),
            self,
        )
        description.setObjectName('descriptionLabel')
        description.setWordWrap(True)
        layout.addWidget(description)

        website_label = QtWidgets.QLabel(self)
        website_label.setObjectName('websiteLabel')
        website_label.setText(
            self._t(
                'Project website: <a href="https://farmanalytica.github.io/fieldguide/">farmanalytica.github.io/fieldguide</a>',
                'Site do projeto: <a href="https://farmanalytica.github.io/fieldguide/">farmanalytica.github.io/fieldguide</a>',
            )
        )
        website_label.setTextFormat(_qt_enum('TextFormat', 'RichText', 'RichText'))
        website_label.setOpenExternalLinks(True)
        website_label.setWordWrap(True)
        layout.addWidget(website_label)

    def _build_capture_group(self, layout):
        """Build map capture section."""
        capture_group = QtWidgets.QGroupBox(
            self._t('Capture', 'Captura'),
            self,
        )
        capture_layout = QtWidgets.QVBoxLayout(capture_group)
        capture_layout.setContentsMargins(10, 12, 10, 10)
        capture_layout.setSpacing(8)

        capture_top_layout = QtWidgets.QHBoxLayout()
        capture_top_layout.setSpacing(8)

        self.mark_on_canvas_checkbox = QtWidgets.QCheckBox(
            self._t('Capture mode (click on map)', 'Modo de captura (clique no mapa)'),
            self,
        )
        capture_top_layout.addWidget(self.mark_on_canvas_checkbox, 1)

        self.capture_status_badge = QtWidgets.QLabel(self)
        self.capture_status_badge.setObjectName('statusBadge')
        capture_top_layout.addWidget(self.capture_status_badge, 0, _qt_enum('AlignmentFlag', 'AlignRight', 'AlignRight'))
        capture_layout.addLayout(capture_top_layout)

        capture_hint = QtWidgets.QLabel(
            self._t(
                'Use this when you want to collect multiple points directly from the canvas.',
                'Use quando quiser coletar varios pontos diretamente no mapa.',
            ),
            self,
        )
        capture_hint.setObjectName('sectionHintLabel')
        capture_hint.setWordWrap(True)
        capture_layout.addWidget(capture_hint)

        self.hybrid_layer_button = QtWidgets.QPushButton(
            self._t('Add Google Hybrid', 'Adicionar Google Hybrid'),
            self,
        )
        self.hybrid_layer_button.setObjectName('hybridButton')
        capture_layout.addWidget(self.hybrid_layer_button)
        layout.addWidget(capture_group)

    def _build_state_group(self, layout):
        """Build session state section."""
        state_group = QtWidgets.QGroupBox(
            self._t('Session State', 'Estado da Sessao'),
            self,
        )
        state_layout = QtWidgets.QVBoxLayout(state_group)
        state_layout.setContentsMargins(10, 12, 10, 10)
        state_layout.setSpacing(8)

        summary_grid = QtWidgets.QGridLayout()
        summary_grid.setHorizontalSpacing(8)
        summary_grid.setVerticalSpacing(6)

        summary_grid.addWidget(QtWidgets.QLabel(self._t('Points', 'Pontos'), self), 0, 0)
        self.point_count_value_label = QtWidgets.QLabel('0', self)
        summary_grid.addWidget(self.point_count_value_label, 0, 1)

        summary_grid.addWidget(QtWidgets.QLabel(self._t('Last point', 'Ultimo ponto'), self), 1, 0)
        self.last_point_value_label = QtWidgets.QLabel(
            self._t('No points yet', 'Nenhum ponto ainda'),
            self,
        )
        self.last_point_value_label.setWordWrap(True)
        summary_grid.addWidget(self.last_point_value_label, 1, 1)

        summary_grid.addWidget(QtWidgets.QLabel(self._t('Route readiness', 'Pronto para rota'), self), 2, 0)
        self.route_status_value_label = QtWidgets.QLabel(
            self._t('Add at least 2 points', 'Adicione ao menos 2 pontos'),
            self,
        )
        self.route_status_value_label.setWordWrap(True)
        summary_grid.addWidget(self.route_status_value_label, 2, 1)

        state_layout.addLayout(summary_grid)

        self.points_list_hint_label = QtWidgets.QLabel(
            self._t(
                'Captured points appear here in collection order.',
                'Os pontos capturados aparecem aqui na ordem de coleta.',
            ),
            self,
        )
        self.points_list_hint_label.setObjectName('sectionHintLabel')
        state_layout.addWidget(self.points_list_hint_label)

        self.points_list_widget = QtWidgets.QListWidget(self)
        self.points_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.points_list_widget.setMinimumHeight(170)
        state_layout.addWidget(self.points_list_widget)
        layout.addWidget(state_group)

    def _build_manual_group(self, layout):
        """Build manual WGS84 input section."""
        manual_group = QtWidgets.QGroupBox(
            self._t('Add Manual Coordinate (WGS84)', 'Adicionar Coordenada Manual (WGS84)'),
            self,
        )
        manual_layout = QtWidgets.QGridLayout(manual_group)
        manual_layout.setContentsMargins(10, 12, 10, 10)
        manual_layout.setHorizontalSpacing(8)
        manual_layout.setVerticalSpacing(6)

        manual_hint = QtWidgets.QLabel(
            self._t(
                'Accepts decimal coordinates with dot or comma separators.',
                'Aceita coordenadas decimais com separador por ponto ou virgula.',
            ),
            self,
        )
        manual_hint.setObjectName('sectionHintLabel')
        manual_hint.setWordWrap(True)
        manual_layout.addWidget(manual_hint, 0, 0, 1, 2)

        manual_layout.addWidget(QtWidgets.QLabel(self._t('Latitude', 'Latitude'), self), 1, 0)
        manual_layout.addWidget(QtWidgets.QLabel(self._t('Longitude', 'Longitude'), self), 1, 1)

        self.manual_latitude_input = QtWidgets.QLineEdit(self)
        self.manual_latitude_input.setPlaceholderText(
            self._t('Latitude (e.g.: -23.550520)', 'Latitude (ex.: -23.550520)')
        )
        manual_layout.addWidget(self.manual_latitude_input, 2, 0)

        self.manual_longitude_input = QtWidgets.QLineEdit(self)
        self.manual_longitude_input.setPlaceholderText(
            self._t('Longitude (e.g.: -46.633308)', 'Longitude (ex.: -46.633308)')
        )
        manual_layout.addWidget(self.manual_longitude_input, 2, 1)

        self.add_manual_coordinate_button = QtWidgets.QPushButton(
            self._t('Add coordinate', 'Adicionar coordenada'),
            self,
        )
        self.add_manual_coordinate_button.setObjectName('manualAddButton')
        manual_layout.addWidget(self.add_manual_coordinate_button, 3, 0, 1, 2)
        layout.addWidget(manual_group)

    def _build_manage_group(self, layout):
        """Build point management section."""
        manage_group = QtWidgets.QGroupBox(
            self._t('Points', 'Pontos'),
            self,
        )
        manage_layout = QtWidgets.QVBoxLayout(manage_group)
        manage_layout.setContentsMargins(10, 12, 10, 10)
        manage_layout.setSpacing(8)

        manage_hint = QtWidgets.QLabel(
            self._t(
                'Remove the last point, clear the session, or open the current route when enough points exist.',
                'Remova o ultimo ponto, limpe a sessao ou abra a rota atual quando houver pontos suficientes.',
            ),
            self,
        )
        manage_hint.setObjectName('sectionHintLabel')
        manage_hint.setWordWrap(True)
        manage_layout.addWidget(manage_hint)

        self.route_all_points_button = QtWidgets.QPushButton(
            self._t('Open route in Google Maps', 'Abrir rota no Google Maps'),
            self,
        )
        self.route_all_points_button.setObjectName('routeAllButton')
        manage_layout.addWidget(self.route_all_points_button)

        destructive_layout = QtWidgets.QHBoxLayout()
        destructive_layout.setSpacing(8)

        self.remove_last_mark_button = QtWidgets.QPushButton(
            self._t('Remove last mark', 'Remover ultima marcacao'),
            self,
        )
        self.remove_last_mark_button.setObjectName('removeLastButton')
        destructive_layout.addWidget(self.remove_last_mark_button)

        self.clear_marks_button = QtWidgets.QPushButton(
            self._t('Clear marks', 'Limpar marcacoes'),
            self,
        )
        self.clear_marks_button.setObjectName('clearButton')
        destructive_layout.addWidget(self.clear_marks_button)

        manage_layout.addLayout(destructive_layout)
        layout.addWidget(manage_group)

    def _build_output_group(self, layout):
        """Build import, export, and report section."""
        output_group = QtWidgets.QGroupBox(
            self._t('Import / Export', 'Importacao / Exportacao'),
            self,
        )
        output_layout = QtWidgets.QVBoxLayout(output_group)
        output_layout.setContentsMargins(10, 12, 10, 10)
        output_layout.setSpacing(8)

        output_hint = QtWidgets.QLabel(
            self._t(
                'Import coordinates from CSV, export the current session, or generate the field PDF report.',
                'Importe coordenadas de CSV, exporte a sessao atual ou gere o PDF de campo.',
            ),
            self,
        )
        output_hint.setObjectName('sectionHintLabel')
        output_hint.setWordWrap(True)
        output_layout.addWidget(output_hint)

        csv_actions_layout = QtWidgets.QHBoxLayout()
        csv_actions_layout.setSpacing(8)

        self.import_csv_button = QtWidgets.QPushButton(
            self._t('Import points CSV', 'Importar pontos CSV'),
            self,
        )
        self.import_csv_button.setObjectName('csvImportButton')
        csv_actions_layout.addWidget(self.import_csv_button)

        self.export_csv_button = QtWidgets.QPushButton(
            self._t('Export points CSV', 'Exportar pontos CSV'),
            self,
        )
        self.export_csv_button.setObjectName('csvExportButton')
        csv_actions_layout.addWidget(self.export_csv_button)

        output_layout.addLayout(csv_actions_layout)

        separator = QtWidgets.QFrame(self)
        separator.setObjectName('lineSeparator')
        separator.setFrameShape(QtWidgets.QFrame.HLine)
        output_layout.addWidget(separator)

        self.generate_pfd_button = QtWidgets.QPushButton(
            self._t('Generate PDF', 'Gerar PDF'),
            self,
        )
        self.generate_pfd_button.setObjectName('generateButton')
        output_layout.addWidget(self.generate_pfd_button)
        layout.addWidget(output_group)

    def _build_about_group(self, layout):
        """Build low-priority about section."""
        about_group = QtWidgets.QGroupBox(
            self._t('About', 'Sobre'),
            self,
        )
        about_layout = QtWidgets.QHBoxLayout(about_group)
        about_layout.setContentsMargins(10, 12, 10, 10)
        about_layout.setSpacing(10)

        sponsor_logo_label = QtWidgets.QLabel(self)
        align_left = _qt_enum('AlignmentFlag', 'AlignLeft', 'AlignLeft')
        align_top = _qt_enum('AlignmentFlag', 'AlignTop', 'AlignTop')
        sponsor_logo_label.setAlignment(align_left | align_top)
        sponsor_logo_path = os.path.join(os.path.dirname(__file__), 'farm_icon.png')
        sponsor_logo_pixmap = QtGui.QPixmap(sponsor_logo_path)
        if not sponsor_logo_pixmap.isNull():
            sponsor_logo_label.setPixmap(
                sponsor_logo_pixmap.scaled(
                    168,
                    48,
                    _qt_enum('AspectRatioMode', 'KeepAspectRatio', 'KeepAspectRatio'),
                    _qt_enum('TransformationMode', 'SmoothTransformation', 'SmoothTransformation'),
                )
            )
        sponsor_logo_label.setFixedSize(172, 52)
        about_layout.addWidget(sponsor_logo_label)

        project_note = QtWidgets.QLabel(self)
        project_note.setWordWrap(True)
        project_note.setText(
            self._t(
                'This is a free and open project, developed with support from <a href="https://farmanalytica.com.br">FARM Analytica</a>. Contact us for custom commercial solutions.',
                'Este e um projeto gratis e aberto, desenvolvido com o apoio da <a href="https://farmanalytica.com.br">FARM Analytica</a>. Entre em contato para solucoes comerciais personalizadas.',
            )
        )
        project_note.setTextFormat(_qt_enum('TextFormat', 'RichText', 'RichText'))
        project_note.setOpenExternalLinks(True)
        project_note.setObjectName('sectionHintLabel')
        about_layout.addWidget(project_note, 1)
        layout.addWidget(about_group)

    def update_capture_status(self, enabled):
        """Show current capture mode status in the header badge."""
        self.capture_status_badge.setProperty('inactive', not enabled)
        self.capture_status_badge.setText(
            self._t('Capture ON', 'Captura ON')
            if enabled
            else self._t('Capture OFF', 'Captura OFF')
        )
        self.capture_status_badge.style().unpolish(self.capture_status_badge)
        self.capture_status_badge.style().polish(self.capture_status_badge)

    def set_points(self, coordinates):
        """Refresh the session summary and point list widgets."""
        coordinates = list(coordinates)
        point_count = len(coordinates)
        self.point_count_value_label.setText(str(point_count))

        self.points_list_widget.clear()
        if point_count == 0:
            empty_text = self._t(
                'No points captured yet. Turn on capture mode or add coordinates manually.',
                'Nenhum ponto capturado ainda. Ative o modo de captura ou adicione coordenadas manualmente.',
            )
            self.points_list_widget.addItem(empty_text)
            self.points_list_widget.setCurrentRow(0)
            self.points_list_widget.setEnabled(False)
            self.last_point_value_label.setText(self._t('No points yet', 'Nenhum ponto ainda'))
            self.route_status_value_label.setText(
                self._t('Add at least 2 points', 'Adicione ao menos 2 pontos')
            )
        else:
            self.points_list_widget.setEnabled(True)
            for index, (longitude, latitude) in enumerate(coordinates, start=1):
                self.points_list_widget.addItem(
                    self._t(
                        'Point {index}: {lat:.6f}, {lon:.6f}',
                        'Ponto {index}: {lat:.6f}, {lon:.6f}',
                    ).format(index=index, lat=latitude, lon=longitude)
                )
            last_longitude, last_latitude = coordinates[-1]
            self.last_point_value_label.setText(
                '{:.6f}, {:.6f}'.format(last_latitude, last_longitude)
            )
            if point_count >= 2:
                self.route_status_value_label.setText(self._t('Ready', 'Pronto'))
            else:
                self.route_status_value_label.setText(
                    self._t('Add at least 2 points', 'Adicione ao menos 2 pontos')
                )

        self._update_action_states(point_count)

    def _update_action_states(self, point_count):
        """Enable only actions that are valid for the current session state."""
        has_points = point_count > 0
        has_route = point_count >= 2
        self.remove_last_mark_button.setEnabled(has_points)
        self.clear_marks_button.setEnabled(has_points)
        self.export_csv_button.setEnabled(has_points)
        self.generate_pfd_button.setEnabled(has_points)
        self.route_all_points_button.setEnabled(has_route)

    def _t(self, english_text, portuguese_text):
        """Return pt-BR text only when plugin language is Portuguese."""
        if self.plugin_language == 'pt_BR':
            return portuguese_text
        return english_text
